name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout current repository
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'temurin' 

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        install: true
        
    - name: Pull Docker Image
      run: docker pull webforj/sandbox:latest
      
    - name: Build Docker Image 
      run: docker build -t webforj/sandbox:latest . 
    
    - name: Run Docker Container 
      run: docker run -d -p 8888:8888 --name my-container webforj/sandbox:latest
    
    - name: Install Maven inside Docker container
      run: docker exec my-container mvn install -e -DskipTests

    - name: Build Docker
      run: docker buildx create --use
        
    - name: Install maven
      run: mvn install -e -DskipTests

    - name: Checkout DemoTester repository
      uses: actions/checkout@v2
      with:
        repository: lschuetz736/demotester2
        path: demotester

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Compile and run java program
      run: cd demotester && mvn compile -e exec:java -D exec.mainClass="org.tester.DemoTester" -D exec.args="compareScreenshots .. default default"

    - name: Upload output file
      uses: actions/upload-artifact@v3
      with:
        name: output-file
        path: demotester/data.txt